### ISSUE TITLE
module not found error cannot resolve module

### ISSUE THREAD

**Issue by golflv100** [mindmup/mapjs-webpack-example#1]
i got this warn on step 1 and i think thats not the problem. i'm using windows x64
![untitled](https://cloud.githubusercontent.com/assets/14575525/23150213/749575bc-f824-11e6-9e28-67129a6e196d.png)

and i got this error on step 2 (this is my ubuntu pc)
![16900125_10210485475206974_1914566956_n](https://cloud.githubusercontent.com/assets/14575525/23150221/856c0040-f824-11e6-963d-aeede6ed0fd1.png)

i don't know what does it mean and how can i fix it

my npm and webpack is latest version
btw i'm so newbie about npm or webpack stuff

**Comment by gojko** [comment]
webpack is not finding dependencies, so you need to install dependencies first properly. this is most likely an issue with your NPM setup.
